[package]
name = "modern-win-gui"
version = "0.1.0"
edition = "2021"

[workspace]
default-members = ["."]
members = [
    ".",
    "lib/codegen",
    "lib/windows-ext"
]

[dependencies]
windows-ext = { path = "lib/windows-ext" }
windows = { version = "0.51", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging"
]}

[build-dependencies]
embed-manifest = "1.4"