name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:
    types: [published]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:

    runs-on: windows-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: hotkey
    - name: Build release
      run: cargo build --release --verbose --target x86_64-pc-windows-msvc
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: target/x86_64-pc-windows-msvc/release/rusty-twinkle-tray.exe
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/x86_64-pc-windows-msvc/release/rusty-twinkle-tray.exe
        tag_name: hotkey
